### ISSUE TITLE
More Detailed Information on CC2350 Firmware

### ISSUE THREAD

**Issue by cdolar** [patience4711/read-APS-inverters-YC600-QS1#1]
Thanks a 1000 times for the hard work you have put into this project.
Since I am an owner of an APSystems YC600 I really am interested in getting your project to work for me, too.

You mentioned the thread https://github.com/Koenkk/zigbee2mqtt/issues/4221 for the CC2350 firmware, which needs to be flashed. Unfortunately, the thread has 500+ entries and the information is well hidden. Also, not all links still work that are mentioned in the thread.

Could you please provide a more detailed link, e.g. to a specific comment in this thread, or could you please add a more detailed description here which firmware has to be flashed exactly?

Thanks a lot and best regards.
Carsten

**Comment by patience4711** [comment]
If you download this package, you'l have all the information, and the firmware for the cc2530. 

https://1drv.ms/u/s!AkMG5FvUwhedimnUoBjQROkAaofW?e=zFgWdM

Good luck
