### ISSUE TITLE
WIFI Password

### ISSUE THREAD

**Issue by kentbrock** [patience4711/read-APS-inverters-YC600-QS1#6]
Hi patience4711,

I have tried to connect to my standard wifi. Fritzbox, WPA2, 63 characters and numbers, only book letters in large and small. Unfortunately this did not work.
Then I tried to connect to my guest account. Here is a much shorter password selected. 14 characters upper and lower case and numbers. With this it worked.

Can it be that the WIFI password length causes problems? 

Many greetings

Markus  

P.S.: Great work.

**Comment by patience4711** [comment]
Sure, this can be 40 characters max,

**Comment by kentbrock** [comment]
Would it be possible to extend the maximum length to 63 characters? This would really help me
